# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/aca21111-a488-4bc7-90a7-e61517c24818";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/aca21111-a488-4bc7-90a7-e61517c24818";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1AC2-9317";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/aca21111-a488-4bc7-90a7-e61517c24818";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/media/data" =
    { device = "/dev/disk/by-uuid/ba796824-5165-4a95-87c2-1fb49a449138";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."data".device = "/dev/disk/by-uuid/3de20c8e-2c31-491a-a8cc-fea4762e8601";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b134fecf-719f-45af-b317-001e413f06c4"; }
    ];

  nix.maxJobs = lib.mkDefault 16;
}
